//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSubType
    {
        public EventSubType()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public int Type_ID { get; set; }
        public string SubType_Name { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
