//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public int SubType_ID { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> Institute_ID { get; set; }
        public string Description { get; set; }
        public string Agent { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public bool AlertDone { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual EventSubType EventSubType { get; set; }
        public virtual Institute Institute { get; set; }
    }
}
