//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.EventSubTypes = new HashSet<EventSubType>();
        }
    
        public int ID { get; set; }
        public string Type_Name { get; set; }
        public int Type_Category { get; set; }
    
        public virtual EventTypeCategory EventTypeCategory { get; set; }
        public virtual ICollection<EventSubType> EventSubTypes { get; set; }
    }
}
