//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HypnosisEntities : DbContext
    {
        public HypnosisEntities()
            : base("name=HypnosisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EventSubType> EventSubTypes { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<EventTypeCategory> EventTypeCategories { get; set; }
        public DbSet<Person> Persons { get; set; }
        public DbSet<Institute> Institutes { get; set; }
        public DbSet<Agent> Agents { get; set; }
        public DbSet<Event> Events { get; set; }
    }
}
