//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institute
    {
        public Institute()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string MainPhone { get; set; }
        public string Phones { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public bool InMailingList { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Address_Comments { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
