//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Events = new HashSet<Event>();
            this.PersonsProjects = new HashSet<PersonsProject>();
        }
    
        public int ID { get; set; }
        public string TZ { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public bool Person_Senior { get; set; }
        public string DisplayName { get; set; }
        public string Mobile { get; set; }
        public string Phones { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public bool InMailingList { get; set; }
        public string Ministry_CaseNumber { get; set; }
        public string Psyhology_LicenseNumber { get; set; }
        public string Psyhology_Specialization { get; set; }
        public string Medicine_LicenseNumber { get; set; }
        public string Medicine_Specialization { get; set; }
        public string Stomatology_LicenseNumber { get; set; }
        public string Stomatology_Specialization { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address_Comments { get; set; }
        public string Degree { get; set; }
        public string ImageOriginalName { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<PersonsProject> PersonsProjects { get; set; }
    }
}
