//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypnosis.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Events = new HashSet<Event>();
            this.PersonsProjects = new HashSet<PersonsProject>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
        public string ImageName { get; set; }
        public string ImageOriginalName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<PersonsProject> PersonsProjects { get; set; }
    }
}
